---
title: "linear"
author:
  - yhj
documentclass: ctexart
keywords:
  - 中文
  - R Markdown
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```









#### paralel S7-S12

```{r}
# Set up the parallel environment (for Windows using makeCluster)
library(parallel)

# Number of cores
cl <- makeCluster(12)  # Number of cores to use

# Export external functions and libraries to the cluster
# clusterExport(cl, c("external_infor", "simu_glm", "set.seed", "betaxin_total", "final_try1", "final_try2","final_try3","final_try4","final_try5","final_try6"))

# Ensure external functions are sourced on each worker node
clusterEvalQ(cl, {
  library(msm)
  library(nloptr)
  library(MASS)
  library(xtable)
  source(file = "d:/tbzs/tb/groupmeeting/paper1/reference sample/linear/r_file2/external_functions.r")
  source(file="d:/tbzs/tb/groupmeeting/paper1/reference sample/linear/r_file2/other_functions.r")
  source(file="d:/tbzs/tb/groupmeeting/paper1/reference sample/linear/r_file2/main_simulation.r")
  source(file = "d:/tbzs/tb/groupmeeting/paper1/reference sample/linear/r_file2/assesment.R")
  
})

# Function to run simulations in parallel
run_simulation <- function(i) {
  # Now the necessary libraries and functions are sourced in the worker environment
  if (i == 1) {
    set.seed(3549)
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.1),NN = 50000,m=1,sig_y =0.8 ,var_if = F)
  set.seed(3333)
final_try1<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.1),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )
    return(final_try1)
  } 
  else if(i==2) {
    set.seed(3549)
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.1),NN = 50000,m=1,sig_y =0.8 ,var_if = F)
  set.seed(3333)
final_try2<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =c(1.2*c(-2.4,-0.5,0.4,0.3,0.65)+c(0.5,0,0,0,0),0.1),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )

    return(final_try2)
  }
  else if(i==3) {
    set.seed(3549)
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.1),NN = 50000,m=1,sig_y =0.8 ,var_if = F)
  set.seed(3333)
final_try3<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =1.2*c(-2.4,-0.5,0.4,0.3,0.65,0.1)-c(0.5,0,0,0,0,0),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )
return(final_try3)
  }
  else if(i==4) {
    set.seed(3549) #102
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.5),NN = 50000,m=1000,sig_y =0.8 ,var_if = F)
  set.seed(3333)
final_try4<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.5),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )

return(final_try4)
  }
  else if(i==5) {
    set.seed(3549) #102
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.5),NN = 50000,m=1000,sig_y =0.8 ,var_if = F)
set.seed(3333)
final_try5<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =c(1.2*c(-2.4,-0.5,0.4,0.3,0.65)+c(0.5,0,0,0,0),0.5),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )

return(final_try5)
  }
  else if(i==6) {
    set.seed(3549) #102
  betaxin_total=external_infor(target_beta =c(-2.4,-0.5,0.4,0.3,0.65,0.5),NN = 50000,m=1000,sig_y =0.8 ,var_if = F)
  set.seed(3333)

final_try6<-simu_linear(betaxin_total = betaxin_total,type_ini = 1,source_beta =1.2*c(-2.4,-0.5,0.4,0.3,0.65,0.5)-c(0.5,0,0,0,0,0),ns=2000,N_r =1000,al_type ="NLOPT_LD_MMA",random_target = F,nt = 500000,vartype = 0,nr=2000 )
return(final_try6)
  }
  
}

clusterExport(cl, varlist = "run_simulation")
# Run simulations in parallel
results <- parLapply(cl, 1:6, function(i) {
  tryCatch({
    run_simulation(i)
  }, error = function(e) {
    list(error = TRUE, message = e$message, node = i)
  })
})
#results<- parLapply(cl, 1:6, run_simulation)

# Stop the cluster after execution
stopCluster(cl)

# Access results
final_try1 <- results[[1]]
final_try2 <- results[[2]]
final_try3 <- results[[3]]
final_try4 <- results[[4]]
final_try5 <- results[[5]]
final_try6 <- results[[6]]
```

```{r}
library(xtable)
  source(file = "d:/tbzs/tb/groupmeeting/paper1/reference sample/linear/r_file2/assesment.R")
  targetbeta=c(-2.4,-0.5,0.4,0.3,0.65,0.5)
assesment_r1<-assesment(result = final_try6,targetbeta = targetbeta)
 print(xtable(assesment_r1,digits = 3),type="latex",sanitize.text.function = function(x){x},include.colnames = F,include.rownames = F)

```





